# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: ~
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }

fos_rest:

  body_converter:
    enabled: true
    validate: true
  body_listener:
    enabled: true
    throw_exception_on_unsupported_content_type:  true
    default_format: json
  param_fetcher_listener: true
  serializer:
    serialize_null: true
  routing_loader:
    default_format:  json
    include_format:  false
  format_listener:
    enabled: true
    rules:
    - { path: ^/, priorities: [ json, jsonp ], fallback_format: json, prefer_extension: false }
    - { path: '^/', stop: true }
  exception:
    enabled: false