nelmio_api_doc:
    documentation:
        info:
            title: GitHub Analyzer
            description: App for repositories comparsion
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
             - ^/compare
