nginx:
    container_name: repo-analyzer-nginx
    image: nginx
    ports:
        - 10083:80
    volumes:
        - ./docker/nginx:/etc/nginx/conf.d
        - ./:/var/www
    links:
        - php

php:
    container_name: repo-analyzer-php
    image: myprod/php:7.3-dev
    volumes:
        - ./:/var/www
        - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
        - 19000:9000

